name: iida
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1m=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.0.0
    - configargparse==1.5.3
    - cython==0.29.28
    - docker-pycreds==0.4.0
    - fasteners==0.17.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glfw==2.5.1
    - gym==0.23.0
    - gym-notices==0.0.5
    - idna==3.3
    - imageio==2.16.1
    - importlib-metadata==4.11.2
    - mujoco-py==2.1.2.14
    - numpy==1.22.3
    - numpy-quaternion==2022.2.10.14.20.39
    - pathtools==0.1.2
    - pillow==9.0.1
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.0
    - pycparser==2.21
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.27.1
    - sentry-sdk==1.5.7
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - six==1.16.0
    - smmap==5.0.0
    - termcolor==1.1.0
    - torch==1.10.2
    - torchgeometry==0.1.2
    - tqdm==4.63.0
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - wandb==0.12.11
    - yaspin==2.1.0
    - zipp==3.7.0
prefix: /home/bne215/anaconda3/envs/iida
